### ISSUE TITLE
Implement MainSettings

### ISSUE THREAD

**Issue by groundh0g** [groundh0g/StimDeck#18]
## Overview

The app needs settings that are scoped to all columns.

## Tasks

On main navigation bar, implement the following features:

- [ ] add column
- [ ] reload all columns
- [ ] settings:
  - [ ] theme selection
  - [ ] column width: SM/MD/LG
  - [ ] mute:
    - [ ] keywords
    - [ ] max hashtag count
    - [ ] whitelist users
      - [ ] users: list of users
      - [ ] my followers
      - [ ] those i follow

**Comment by groundh0g** [comment]
Mockup source:

```html
<samp>
    <div>
        <ul>
            <li>Theme:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DROPDOWN]</li>
            <li>Column&nbsp;Size:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DROPDOWN]</li>
            <li>Reload&nbsp;Columns:&nbsp;[RELOAD ALL]</li>
            <li>Close&nbsp;Columns:&nbsp;&nbsp;&nbsp;[CLOSE ALL]</li>
            <li><strong>Mute Options:</strong></li>
            <li>&nbsp;&nbsp;Keywords:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EDIT]</li>
            <li>&nbsp;&nbsp;Max&nbsp;Hashtags:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[9999]</li>
            <li>&nbsp;&nbsp;Max&nbsp;Mentions:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[9999]</li>
            <li><strong>Whitelist:</strong></li>
            <li>&nbsp;&nbsp;Users:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EDIT]</li>
            <li>&nbsp;&nbsp;Followers:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[YES/NO]</li>
            <li>&nbsp;&nbsp;Following:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[YES/NO]</li>
        </ul>
    </div>
</samp>
```
